# Generated by Django 2.2.6 on 2019-10-13 00:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('content_object', models.TextField()),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('field', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(max_length=20)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
    ]
